name: It's Cute
title: Moda, Beleza e muitas dicas
email: contato@itscute.com.br
description: >- # this means to ignore newlines until "baseurl:"
  Olá me chamo Bruna e este é o It's Cute, um blog cheio de dicas sobre moda e beleza.
  Fique por dentro das novidades aqui no It's Cute.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itscute.luanmessias.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
permalink: /:title
plugins:
  - jekyll-feed
  - jekyll-babel

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: itscute


sass:
  style: compressed
  sourcemap: true
  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
